### YamlMime:Yaml
ms.openlocfilehash: 3352701416de64fec0cc1b092f0daeff07c028bc
ms.sourcegitcommit: 334e84b4aed63162bcc31831cffd6d363dafee02
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 11/29/2018
ms.locfileid: "27994229"
version: 1.0.{build}
clone_depth: 1
build_script:
- ps: Write-Host "no build required"
test_script:
- ps: >-
    $scriptPath = Join-Path $env:APPVEYOR_BUILD_FOLDER -ChildPath "Test-Docs.ps1"

    & $scriptPath

    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#build-status'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
